# Generated by Django 3.1 on 2020-08-22 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='value',
            new_name='amount',
        ),
    ]
